In [22]:
import pandas as pd
import numpy as np
#read csv
df = pd.read_csv(r"data\new_retail_data.csv")
pd.set_option('display.max_columns', None)
pd.set_option('future.no_silent_downcasting', True)
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788.0,37249.0,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985.0,Germany,21.0,Male,Low,Regular,9/18/2023,2023.0,September,22:03:55,3.0,108.028757,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773.0,69749.0,Kelsey Hill,Mark36@gmail.com,6.852900e+09,82072 Dawn Centers,Nottingham,England,99071.0,UK,19.0,Female,Low,Premium,12/31/2023,2023.0,December,8:42:04,2.0,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610.0,30192.0,Scott Jensen,Shane85@gmail.com,8.362160e+09,4133 Young Canyon,Geelong,New South Wales,75929.0,Australia,48.0,Male,Low,Regular,4/26/2023,2023.0,April,4:06:29,3.0,354.477600,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460.0,62101.0,Joseph Miller,Mary34@gmail.com,2.776752e+09,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420.0,Canada,56.0,Male,High,Premium,5/8/2023,2023.0,May,14:55:17,7.0,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775.0,27901.0,Debra Coleman,Charles30@gmail.com,9.098268e+09,5813 Lori Ports Suite 269,Bristol,England,48704.0,UK,22.0,Male,Low,Premium,1/10/2024,2024.0,January,16:54:07,2.0,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [24]:
# Drop duplicates
df.drop_duplicates(inplace=True)

In [26]:
#Replace NAN values with empty string
df = df.replace(np.nan, '')

In [28]:
#Convert numeric columns to integer
cols = ['Transaction_ID','Customer_ID','Zipcode','Age','Year','Total_Purchases']
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')  
df[cols] = df[cols].fillna(0).astype(np.int64)

In [30]:
#Format Phone number to a standard form
df['Phone']=df['Phone'].apply(lambda x: str(x))
df['Phone']= df['Phone'].apply(lambda x: x[0:3]+'-'+x[3:6]+'-'+x[6:10])
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,9/18/2023,2023,September,22:03:55,3,108.028757,324.08627,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,685-289-9987,82072 Dawn Centers,Nottingham,England,99071,UK,19,Female,Low,Premium,12/31/2023,2023,December,8:42:04,2,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,836-216-0449,4133 Young Canyon,Geelong,New South Wales,75929,Australia,48,Male,Low,Regular,4/26/2023,2023,April,4:06:29,3,354.4776,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,277-675-1724,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,56,Male,High,Premium,5/8/2023,2023,May,14:55:17,7,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,909-826-7635,5813 Lori Ports Suite 269,Bristol,England,48704,UK,22,Male,Low,Premium,1/10/2024,2024,January,16:54:07,2,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [32]:
# Convert object column to datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Format the date as day-month-year
df['Date'] = df['Date'].dt.strftime('%d-%m-%Y')

df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,18-09-2023,2023,September,22:03:55,3,108.028757,324.08627,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,685-289-9987,82072 Dawn Centers,Nottingham,England,99071,UK,19,Female,Low,Premium,31-12-2023,2023,December,8:42:04,2,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,836-216-0449,4133 Young Canyon,Geelong,New South Wales,75929,Australia,48,Male,Low,Regular,26-04-2023,2023,April,4:06:29,3,354.4776,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,277-675-1724,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,56,Male,High,Premium,08-05-2023,2023,May,14:55:17,7,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,909-826-7635,5813 Lori Ports Suite 269,Bristol,England,48704,UK,22,Male,Low,Premium,10-01-2024,2024,January,16:54:07,2,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [34]:
# Convert object column to datetime
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M', errors='coerce')

# Format time to show hours and minutes only
df['Time'] = df['Time'].dt.strftime('%H:%M')

df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,18-09-2023,2023,September,NaN,3,108.028757,324.08627,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,685-289-9987,82072 Dawn Centers,Nottingham,England,99071,UK,19,Female,Low,Premium,31-12-2023,2023,December,NaN,2,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,836-216-0449,4133 Young Canyon,Geelong,New South Wales,75929,Australia,48,Male,Low,Regular,26-04-2023,2023,April,NaN,3,354.4776,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,277-675-1724,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,56,Male,High,Premium,08-05-2023,2023,May,NaN,7,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,909-826-7635,5813 Lori Ports Suite 269,Bristol,England,48704,UK,22,Male,Low,Premium,10-01-2024,2024,January,NaN,2,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [36]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [38]:
df['Age'] = df['Age'].replace('', pd.NA)
df['Total_Amount'] = df['Total_Amount'].replace('', pd.NA)
df['Total_Purchases'] = df['Total_Purchases'].replace('', pd.NA)

# Convert columns to numeric, forcing non-convertible values to NaN
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Total_Amount'] = pd.to_numeric(df['Total_Amount'], errors='coerce')
df['Total_Purchases'] = pd.to_numeric(df['Total_Purchases'], errors='coerce')

# Check for NaN values in the DataFrame
print(df.isnull().sum())

Transaction_ID           0
Customer_ID              0
Name                     0
Email                    0
Phone                    0
Address                  0
City                     0
State                    0
Zipcode                  0
Country                  0
Age                      0
Gender                   0
Income                   0
Customer_Segment         0
Date                   359
Year                     0
Month                    0
Time                302006
Total_Purchases          0
Amount                   0
Total_Amount           350
Product_Category         0
Product_Brand            0
Product_Type             0
Feedback                 0
Shipping_Method          0
Payment_Method           0
Order_Status             0
Ratings                  0
products                 0
dtype: int64

In [40]:
df['Amount'] = df['Amount'].replace('',0)
df['Total_Amount'] = df['Total_Amount'].fillna(df['Total_Purchases']*df['Amount'])
df['Date'] = df['Date'].fillna('')
df['Time'] = df['Time'].fillna('')

In [42]:
df['Total_Amount'] = pd.to_numeric(df['Total_Amount'], errors='coerce')

In [44]:
df.isnull().sum()

Transaction_ID      0
Customer_ID         0
Name                0
Email               0
Phone               0
Address             0
City                0
State               0
Zipcode             0
Country             0
Age                 0
Gender              0
Income              0
Customer_Segment    0
Date                0
Year                0
Month               0
Time                0
Total_Purchases     0
Amount              0
Total_Amount        0
Product_Category    0
Product_Brand       0
Product_Type        0
Feedback            0
Shipping_Method     0
Payment_Method      0
Order_Status        0
Ratings             0
products            0
dtype: int64

In [46]:
# Filter dataset for customers from Germany
df = df[df['Country'] == 'Germany']
# Display first few rows
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,18-09-2023,2023,September,,3,108.03,324.09,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.00,Cycling shorts
7,2344675,26603,Angela Fields,Tanya94@gmail.com,366-809-6144,237 Young Curve,Munich,Berlin,86862,Germany,29,Male,Medium,Premium,24-03-2023,2023,March,,1,46.59,46.59,Clothing,Zara,Shirt,Bad,Same-Day,Cash,Processing,1.00,Dress shirt
9,4926148,31878,Lori Bell,Jessica33@gmail.com,600-489-5059,6225 William Lodge,Cologne,Berlin,64317,Germany,25,Male,Medium,New,04-10-2023,2023,October,,10,397.61,3976.11,Home Decor,Home Depot,Decorations,Excellent,Standard,Cash,Delivered,4.00,Candles
17801,3680043,78484,Mr. Zachary Marks,Tyler6@gmail.com,283-149-9082,085 Nguyen Highway,Cologne,Berlin,49173,Germany,19,Female,Medium,New,28-12-2023,2023,December,,9,274.98,2474.86,Home Decor,Home Depot,Tools,Good,Express,PayPal,Delivered,4.00,Drill
17810,5206426,66989,Angel Fitzpatrick,Evan31@gmail.com,749-002-3454,548 Gonzalez Camp,Leipzig,Berlin,95501,Germany,19,Male,Medium,New,06-06-2023,2023,June,,2,85.72,171.44,Grocery,Coca-Cola,Water,Excellent,Standard,Debit Card,Delivered,5.00,Flavored water

In [48]:
# Dictionary mapping cities in Germany to their correct states
german_city_to_state = {
    "Berlin": "Berlin",
    "Hamburg": "Hamburg",
    "Munich": "Bavaria",
    "Cologne": "North Rhine-Westphalia",
    "Frankfurt": "Hesse",
    "Stuttgart": "Baden-Württemberg",
    "Düsseldorf": "North Rhine-Westphalia",
    "Dortmund": "North Rhine-Westphalia",
    "Essen": "North Rhine-Westphalia",
    "Leipzig": "Saxony",
    "Bremen": "Bremen",
    "Dresden": "Saxony",
    "Hanover": "Lower Saxony",
    "Nuremberg": "Bavaria",
    "Duisburg": "North Rhine-Westphalia",
    "Bochum": "North Rhine-Westphalia",
    "Wuppertal": "North Rhine-Westphalia",
    "Bielefeld": "North Rhine-Westphalia",
    "Bonn": "North Rhine-Westphalia",
    "Münster": "North Rhine-Westphalia",
    "Karlsruhe": "Baden-Württemberg",
    "Mannheim": "Baden-Württemberg",
    "Augsburg": "Bavaria",
    "Wiesbaden": "Hesse",
    "Gelsenkirchen": "North Rhine-Westphalia",
    "Mönchengladbach": "North Rhine-Westphalia",
    "Braunschweig": "Lower Saxony",
    "Kiel": "Schleswig-Holstein",
    "Aachen": "North Rhine-Westphalia",
    "Chemnitz": "Saxony",
    "Halle (Saale)": "Saxony-Anhalt",
    "Magdeburg": "Saxony-Anhalt",
    "Freiburg im Breisgau": "Baden-Württemberg",
    "Krefeld": "North Rhine-Westphalia",
    "Lübeck": "Schleswig-Holstein",
    "Oberhausen": "North Rhine-Westphalia",
    "Erfurt": "Thuringia",
    "Mainz": "Rhineland-Palatinate",
    "Rostock": "Mecklenburg-Western Pomerania",
    "Kassel": "Hesse",
    "Hagen": "North Rhine-Westphalia",
    "Hamm": "North Rhine-Westphalia",
    "Saarbrücken": "Saarland",
    "Mülheim an der Ruhr": "North Rhine-Westphalia",
    "Potsdam": "Brandenburg",
    "Ludwigshafen am Rhein": "Rhineland-Palatinate",
    "Oldenburg": "Lower Saxony",
    "Leverkusen": "North Rhine-Westphalia",
    "Osnabrück": "Lower Saxony",
    "Solingen": "North Rhine-Westphalia",
    "Heidelberg": "Baden-Württemberg",
    "Herne": "North Rhine-Westphalia",
    "Neuss": "North Rhine-Westphalia",
    "Darmstadt": "Hesse",
    "Paderborn": "North Rhine-Westphalia",
    "Regensburg": "Bavaria",
    "Ingolstadt": "Bavaria",
    "Würzburg": "Bavaria",
}

# Update the state column based on the city
df["State"] = df["City"].map(german_city_to_state).fillna(df["State"])

df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,North Rhine-Westphalia,77985,Germany,21,Male,Low,Regular,18-09-2023,2023,September,,3,108.03,324.09,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.00,Cycling shorts
7,2344675,26603,Angela Fields,Tanya94@gmail.com,366-809-6144,237 Young Curve,Munich,Bavaria,86862,Germany,29,Male,Medium,Premium,24-03-2023,2023,March,,1,46.59,46.59,Clothing,Zara,Shirt,Bad,Same-Day,Cash,Processing,1.00,Dress shirt
9,4926148,31878,Lori Bell,Jessica33@gmail.com,600-489-5059,6225 William Lodge,Cologne,North Rhine-Westphalia,64317,Germany,25,Male,Medium,New,04-10-2023,2023,October,,10,397.61,3976.11,Home Decor,Home Depot,Decorations,Excellent,Standard,Cash,Delivered,4.00,Candles
17801,3680043,78484,Mr. Zachary Marks,Tyler6@gmail.com,283-149-9082,085 Nguyen Highway,Cologne,North Rhine-Westphalia,49173,Germany,19,Female,Medium,New,28-12-2023,2023,December,,9,274.98,2474.86,Home Decor,Home Depot,Tools,Good,Express,PayPal,Delivered,4.00,Drill
17810,5206426,66989,Angel Fitzpatrick,Evan31@gmail.com,749-002-3454,548 Gonzalez Camp,Leipzig,Saxony,95501,Germany,19,Male,Medium,New,06-06-2023,2023,June,,2,85.72,171.44,Grocery,Coca-Cola,Water,Excellent,Standard,Debit Card,Delivered,5.00,Flavored water

In [50]:
df.to_csv("cleaned-dataset-germany.csv", index=False) #saving the dataframe