In [237]:
import pandas as pd
import numpy as np

In [239]:
#read csv
df = pd.read_csv(r"C:\Users\Sarah\Documents\Data Analysis Project\Retail\retail-data-analysis\data\new_retail_data.csv")
pd.set_option('display.max_columns', None)
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788.0,37249.0,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985.0,Germany,21.0,Male,Low,Regular,9/18/2023,2023.0,September,22:03:55,3.0,108.028757,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773.0,69749.0,Kelsey Hill,Mark36@gmail.com,6.852900e+09,82072 Dawn Centers,Nottingham,England,99071.0,UK,19.0,Female,Low,Premium,12/31/2023,2023.0,December,8:42:04,2.0,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610.0,30192.0,Scott Jensen,Shane85@gmail.com,8.362160e+09,4133 Young Canyon,Geelong,New South Wales,75929.0,Australia,48.0,Male,Low,Regular,4/26/2023,2023.0,April,4:06:29,3.0,354.477600,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460.0,62101.0,Joseph Miller,Mary34@gmail.com,2.776752e+09,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420.0,Canada,56.0,Male,High,Premium,5/8/2023,2023.0,May,14:55:17,7.0,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775.0,27901.0,Debra Coleman,Charles30@gmail.com,9.098268e+09,5813 Lori Ports Suite 269,Bristol,England,48704.0,UK,22.0,Male,Low,Premium,1/10/2024,2024.0,January,16:54:07,2.0,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [240]:
#remove duplicates
df = df.drop_duplicates()
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788.0,37249.0,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985.0,Germany,21.0,Male,Low,Regular,9/18/2023,2023.0,September,22:03:55,3.0,108.028757,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773.0,69749.0,Kelsey Hill,Mark36@gmail.com,6.852900e+09,82072 Dawn Centers,Nottingham,England,99071.0,UK,19.0,Female,Low,Premium,12/31/2023,2023.0,December,8:42:04,2.0,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610.0,30192.0,Scott Jensen,Shane85@gmail.com,8.362160e+09,4133 Young Canyon,Geelong,New South Wales,75929.0,Australia,48.0,Male,Low,Regular,4/26/2023,2023.0,April,4:06:29,3.0,354.477600,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460.0,62101.0,Joseph Miller,Mary34@gmail.com,2.776752e+09,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420.0,Canada,56.0,Male,High,Premium,5/8/2023,2023.0,May,14:55:17,7.0,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775.0,27901.0,Debra Coleman,Charles30@gmail.com,9.098268e+09,5813 Lori Ports Suite 269,Bristol,England,48704.0,UK,22.0,Male,Low,Premium,1/10/2024,2024.0,January,16:54:07,2.0,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [241]:
#Replace NAN values with empty string
df = df.replace(np.nan, '')

In [242]:
#Convert numeric columns to integer
cols = ['Transaction_ID','Customer_ID','Zipcode','Age','Year','Total_Purchases']
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')  
df[cols] = df[cols].fillna(0).astype(np.int64)

In [243]:
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,1414786801.0,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,9/18/2023,2023,September,22:03:55,3,108.028757,324.08627,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,6852899987.0,82072 Dawn Centers,Nottingham,England,99071,UK,19,Female,Low,Premium,12/31/2023,2023,December,8:42:04,2,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,8362160449.0,4133 Young Canyon,Geelong,New South Wales,75929,Australia,48,Male,Low,Regular,4/26/2023,2023,April,4:06:29,3,354.4776,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,2776751724.0,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,56,Male,High,Premium,5/8/2023,2023,May,14:55:17,7,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,9098267635.0,5813 Lori Ports Suite 269,Bristol,England,48704,UK,22,Male,Low,Premium,1/10/2024,2024,January,16:54:07,2,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [245]:
#Format Phone number to a standard form
df['Phone']=df['Phone'].apply(lambda x: str(x))
df['Phone']= df['Phone'].apply(lambda x: x[0:3]+'-'+x[3:6]+'-'+x[6:10])
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,9/18/2023,2023,September,22:03:55,3,108.028757,324.08627,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,685-289-9987,82072 Dawn Centers,Nottingham,England,99071,UK,19,Female,Low,Premium,12/31/2023,2023,December,8:42:04,2,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,836-216-0449,4133 Young Canyon,Geelong,New South Wales,75929,Australia,48,Male,Low,Regular,4/26/2023,2023,April,4:06:29,3,354.4776,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,277-675-1724,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,56,Male,High,Premium,5/8/2023,2023,May,14:55:17,7,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,909-826-7635,5813 Lori Ports Suite 269,Bristol,England,48704,UK,22,Male,Low,Premium,1/10/2024,2024,January,16:54:07,2,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [253]:
# Convert object column to datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Format the date as day-month-year
df['Date'] = df['Date'].dt.strftime('%d-%m-%Y')

df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,18-09-2023,2023,September,22:03:55,3,108.028757,324.08627,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,685-289-9987,82072 Dawn Centers,Nottingham,England,99071,UK,19,Female,Low,Premium,31-12-2023,2023,December,8:42:04,2,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,836-216-0449,4133 Young Canyon,Geelong,New South Wales,75929,Australia,48,Male,Low,Regular,26-04-2023,2023,April,4:06:29,3,354.4776,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,277-675-1724,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,56,Male,High,Premium,08-05-2023,2023,May,14:55:17,7,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,909-826-7635,5813 Lori Ports Suite 269,Bristol,England,48704,UK,22,Male,Low,Premium,10-01-2024,2024,January,16:54:07,2,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [255]:
# Convert object column to datetime
df['Time'] = pd.to_datetime(df['Time'], errors='coerce')

# Format time to show hours and minutes only
df['Time'] = df['Time'].dt.strftime('%H:%M')

df.head()

C:\Users\Sarah\AppData\Local\Temp\ipykernel_5196\483160429.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(df['Time'], errors='coerce')

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,18-09-2023,2023,September,22:03,3,108.028757,324.08627,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,685-289-9987,82072 Dawn Centers,Nottingham,England,99071,UK,19,Female,Low,Premium,31-12-2023,2023,December,08:42,2,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,836-216-0449,4133 Young Canyon,Geelong,New South Wales,75929,Australia,48,Male,Low,Regular,26-04-2023,2023,April,04:06,3,354.4776,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,277-675-1724,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,56,Male,High,Premium,08-05-2023,2023,May,14:55,7,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,909-826-7635,5813 Lori Ports Suite 269,Bristol,England,48704,UK,22,Male,Low,Premium,10-01-2024,2024,January,16:54,2,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [257]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [261]:
df

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,18-09-2023,2023,September,22:03,3,108.03,324.09,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.00,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,685-289-9987,82072 Dawn Centers,Nottingham,England,99071,UK,19,Female,Low,Premium,31-12-2023,2023,December,08:42,2,403.35,806.71,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.00,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,836-216-0449,4133 Young Canyon,Geelong,New South Wales,75929,Australia,48,Male,Low,Regular,26-04-2023,2023,April,04:06,3,354.48,1063.43,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.00,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,277-675-1724,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,56,Male,High,Premium,08-05-2023,2023,May,14:55,7,352.41,2466.85,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.00,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,909-826-7635,5813 Lori Ports Suite 269,Bristol,England,48704,UK,22,Male,Low,Premium,10-01-2024,2024,January,16:54,2,124.28,248.55,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.00,Chocolate cookies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302005,4246475,12104,Meagan Ellis,Courtney60@gmail.com,746-635-3743,389 Todd Path Apt. 159,Townsville,New South Wales,4567,Australia,31,Male,Medium,Regular,20-01-2024,2024,January,23:40,5,194.79,973.96,Books,Penguin Books,Fiction,Bad,Same-Day,Cash,Processing,1.00,Historical fiction
302006,1197603,69772,Mathew Beck,Jennifer71@gmail.com,575-430-4957,52809 Mark Forges,Hanover,Berlin,16852,Germany,35,Female,Low,New,28-12-2023,2023,December,02:55,1,285.14,285.14,Electronics,Apple,Laptop,Excellent,Same-Day,Cash,Processing,5.00,LG Gram
302007,7743242,28449,Daniel Lee,Christopher100@gmail.com,938-253-0370,407 Aaron Crossing Suite 495,Brighton,England,88038,UK,41,Male,Low,Premium,27-02-2024,2024,February,02:43,3,60.70,182.11,Clothing,Adidas,Jacket,Average,Express,Cash,Shipped,2.00,Parka
302008,9301950,45477,Patrick Wilson,Rebecca65@gmail.com,937-322-2023,3204 Baird Port,Halifax,Ontario,67608,Canada,41,Male,Medium,New,03-09-2023,2023,September,11:20,1,120.83,120.83,Home Decor,IKEA,Furniture,Good,Standard,Cash,Shipped,4.00,TV stand
302009,2882826,53626,Dustin Merritt,William14@gmail.com,951-892-6645,143 Amanda Crescent,Tucson,West Virginia,25242,USA,28,Female,Low,Premium,08-01-2024,2024,January,11:44,7,340.32,2382.23,Home Decor,Home Depot,Decorations,Average,Same-Day,Cash,Shipped,2.00,Clocks